config/routes.rb
Pickr::Application.routes.draw do

  resources :friendships, only: [:create, :destroy]
  devise_for :users
  get "profile/:id" => "users#show", as: 'profile'

  root to: "uploads#index"
  resources :uploads, path: 'pictures'
  get 'friends/uploads' => 'uploads#friend_stream'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  validates_uniqueness_of :user_id, scope: :friend_id
  validate :friend_is_not_self

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def friend_is_not_self
    errors.add("Cannot friend yourself.") if friend_id == user_id
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  default_scope order('created_at DESC')

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :uploads

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  def sent_invites
    inverse = inverse_friend_ids
    sent = friend_ids.select{|id| !inverse.include?(id) }
    friendships.where("friend_id = ?", sent)
  end

  def received_invites
    sent = friend_ids
    inverse = inverse_friend_ids.select{|id| !sent.include?(id) }
    inverse_friendships.where("user_id = ?", inverse)
  end

  def true_friendships
    sent = friend_ids
    inverse = inverse_friend_ids.select{|id| sent.include?(id) }
    inverse_friendships.where("user_id = ?", inverse)
  end

  def add_friend(user)
    Friendship.create!(user_id: self.id, friend_id: user.id)
  end

  def remove_friend(user)
    Friendship.all.where(user_id: self.id, friend_id: user.id).delete_all
    Friendship.all.where(user_id: user.id, friend_id: self.id).delete_all
  end

  def self.friends?(user_a, user_b)
    (Friendship.all.where(user_id: user_a.id, friend_id: user_b.id) +
     Friendship.all.where(user_id: user_a.id, friend_id: user_a.id)).count == 2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friendship = Friendship.find(params[:friendship_id])
    current_user.add_friend(friendship.user)
    redirect_to profile_path(current_user)
  end

  def destroy
    friendship = Friendship.find(params[:friendship_id])
    current_user.remove_friend(friendship.user)
    redirect_to profile_path(current_user)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all(:limit => 10)
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def new
    @upload = Upload.new
  end

  def create
    puts "PARAMETERS #{upload_params}"
    upload = Upload.create(upload_params)
    current_user.uploads << upload
    current_user.save
    redirect_to upload_path(upload)
  end

  def destroy
    @upload = Upload.find(params[:id])
    @upload.delete if @upload.user == current_user
    redirect_to :uploads
  end

  def friend_stream
    @uploads = Upload.all.where("user_id = ?", current_user.friend_ids)
  end

  private
    def upload_params
      params.require(:upload).permit!
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  # private

  # def user_params
  #   params.require(:user).permit!
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '#' %></li>
          <li><%= link_to "Help",    '#' %></li>
          <li><%= link_to "Login", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pickr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
<% if signed_in? %>
  <%= link_to('[logout]', :destroy_user_session, method: :delete) %>
  <%= link_to('[upload]', :new_upload) %>
<% else %>
  <%= link_to('[login]', :user_session, method: :post) %>
<% end %>
<%= link_to('[pictarrgghs]', :uploads) %>
<%= link_to('[friends pictarrgghs]', friends_uploads_path) %>
<%= signed_in? ? link_to('[profile]', profile_path(current_user)) : "" %>
<br>
    <%= yield %>

  </div>
</body>
</html>

app/views/uploads/friend_stream.html.erb
<% @uploads.each do |upload|  %>
  <%= image_tag upload.photo %>
<% end %>

app/views/uploads/index.html.erb
<% @uploads.each do |upload|  %>
  <%= link_to image_tag(upload.photo), upload_path(upload) %>
  <br><br>
<% end %>

app/views/uploads/new.html.erb
<br><br>
<%= form_for @upload, html: { :multipart => true } do |f| %>
  <%= f.file_field :photo %>
  <br>
  <%= f.submit %>
<% end %>

app/views/uploads/show.html.erb
<% if current_user == @upload.user %>
  <br>
  <%= link_to "delete", upload_path(@upload), method: :delete %>
<% end %>
<br>
<%= image_tag @upload.photo %>

app/views/users/show.html.erb
<h3>Profile page</h3>
<%= @user == current_user ? "Welcome back #{current_user.email}" : "Please login" %>

<br>
<h4>Friends</h4>

<% @user.true_friendships.each do |friendship| %>
  <%= friendship.user.email %>
  <%= link_to "delete", friendship_path(:friendship_id => friendship.id), method: :delete %>
<% end %>

<br>
<h4>Friendship request</h4>
<% @user.received_invites.each do |invite| %>
  <%= "#{invite.user.email} wants to meet you" %>
  <%= link_to "accept", friendships_path(:friendship_id => invite.id), method: :post %>
  <%= link_to "decline", friendship_path(:friendship_id => invite.id), method: :delete %>
<% end %>